name: integration-tests

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      INTEGRATIONTEST_RELPATH: 'src/integrationtests-cli/bin/Release/netcoreapp3.1'

    steps:
    - uses: actions/checkout@v1
    - name: 'Hack version in aggregator-manifest.ini'
      run: 'sed -E -i "s/version=.*/version=99.0.0/" ${GITHUB_WORKSPACE}/src/aggregator-function/aggregator-manifest.ini'
      shell: bash

    # compile and test
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
    - name: 'Delete Directory.Build.targets from src/aggregator-function'
      run: rm src/aggregator-function/Directory.Build.targets
    - run: 'dotnet restore src/aggregator-cli.sln'
    - run: 'dotnet build --configuration $env:CONFIGURATION src/aggregator-cli.sln'
    - run: 'dotnet test --configuration $env:CONFIGURATION src/unittests-core/unittests-core.csproj'
    - run: 'dotnet test --configuration $env:CONFIGURATION src/unittests-ruleng/unittests-ruleng.csproj'
    - run: 'dotnet test --configuration $env:CONFIGURATION src/unittests-function/unittests-function.csproj'
    # logon-data.json is stored in project Secrets
    - name: 'Get integration tests secrets'
      run: |
        echo "$LOGONDATA_JSON" > $GITHUB_WORKSPACE/$INTEGRATIONTEST_RELPATH/logon-data.json
        export LOGONDATA_FNAME=$GITHUB_WORKSPACE/$INTEGRATIONTEST_RELPATH/logon-data.json
        INTEGRATIONTEST_SUBSCRIPTIONID=$(jq -r '.subscription?' $LOGONDATA_FNAME)
        echo "Azure subscription for testing: $INTEGRATIONTEST_SUBSCRIPTIONID"
      env:
        LOGONDATA_JSON: ${{ secrets.INTEGRATIONTESTS_CLI_LOGONDATA_JSON }}
      shell: bash
    # heavy weight integration tests
    - run: 'dotnet test --configuration $env:CONFIGURATION .\src\integrationtests-cli-alt\integrationtests-cli-alt.csproj'
    # run anyway
    - name: 'Scrap secrets'
      run: rm $env:GITHUB_WORKSPACE/$env:INTEGRATIONTEST_RELPATH/logon-data.json
      if: always()
